FROM node:16-alpine 

WORKDIR /app

COPY package*.json ./ 

RUN npm install 

COPY . . 

# No need to expose port here, as it's handled in docker-compose.yml

# The command is defined in docker-compose.yml